language: clojure
lein: lein2
jdk:
- oraclejdk8
before_script:
- lein deps
script:
- lein2 kibit
- lein2 test
after_success:
- lein2 uberjar
- lein2 jdeb
env:
  global:
    secure: E831O8ZXVktblY/mztpGBHFgMaeKyfSc6Nory5VtyOFFL59XkVFzJIDdy56kkpYC3mc+ib0h/bm4NA5OjZo5bxPqJ1eHI/FNp/bhk4o3BmGRMAE/Ds6/FMaf5zX2XaBnQJJF8vCYWiMYibzjdm1i86iQeqD0ImgC0Mc379W3mxC4YcEI51SqUemwRKc5xpDEfMH4jjsCyKyJFpUNHXkg2S2asEqPc+NVsVd7B6j08hA0aT0plAPTctgLmQyaDePIYTBbtXNPT84ZZUKm7YK2gMfslXUncoTy58xC/rTpbWE+HhHDfKVaA3ZHimOsPTgob/HIV+f2hrv1N8Px29b0QDxhBRhvQw685zpUp7Q79HNfQisb/L3BNFA1HlxNrG+KjCDhGF+t1TbJP7Fd8qAPSym0yfl9rXz59ArBI3e1h1LTocosrRoVn1ELKACwCCWCDWT5/qmFy5w9rYqPMYUZj/CkFMOls6/2QcPfNEmow2g7wIdTvAslN029xiiqTS1d1NcZ1lgMcnPr/yDz8Pn/uv2Kmv9uTjqtFAxJEI/StXA3T5n1kk8o5bUl8FmGHwClQs+1JW2Cw3LJFOBwVvWLsOclFNGAIucd+kS+8qHCgod2UTB0sUFg1Tq59mf+cc3eK09NRNeJ+N7zuS8t7Fyu656GMVFfj06VqmQbDCE9LLU=
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: MP9flNyfcBJxs35qwwQmQB+LpgH/Lb6oXB2RpydgA180GRsPfwKTqJDhpZDEZ5JO5824QMcp45h36EAunFwnZQsLWD7+z93s7A8qPkRXSEzTpT+TNTkt5Q59ZJXG8PjGel/LrTPeklVqi7FUiN4ugtckEQdXRCoO1PRTsrrdEKlXAsN3obyAZuF8cesmoq1egawmXSdYAm5zQsTWJ7ZOyXjMnTeg8YyduSBdTGjC5tZJyKB1xdtOSCMLOw16lcQzqigf/ZdB9BKj6HRUQTm5JWUbpXJFVshy8jSj0KwnrONwGgHP3p3z5jtZVoi4pConfraxLtb589rEaXv3NeM9cww82eQgB1BEH36JZucCdq/emiiW6w9/6WI+xm75uVufgVDyXNqYBNk6bAsfxvRNvUr+KouOw/4NMudq0m+LkJF7gA4red7Ewqnx4hGYmHCLSPjfS2f41gsar0Kf9kqFGRtkhYu0P55L5j6WGYGb3UpGSF3UiAJtkG6y0rmiLDf1rcvICXu5Zc6AMjl6TseGS2LlUxYbj3j5X5rBOIn7HngjYjvFaMpSXjK6r6FTY68XrddPRuP6C6c6aHrR3wNbv0TAp7k2A2mecJRm6fOQka9Z/uH1OhShlTQ1Cz/o5PJ/DOgs3QLmgaxNYSfEwEzGi8VhYgTZ+Un4Z8OxWIWQrQA=
deploy:
  provider: bintray
  file: bintray.json
  user: karolisl
  key:
    secure: uu5p4hWMGBsnQBnutN8Or8krahaHN8EvgcdOeOJwH4Iezau8TCuARMK0IOjnvnEuw+Zn8ggeJwt5yQf4KyXURBI4RauZY6yNEHUZLHjAWg0ewassdO7zaB2le7Vn88STEQ5RFDrAe8mYpn62Tf1GKCGpLMaGjaHvJbsd1rWsqSt0NqkhbHmUP+xYvYR5yy/B89RiXkHHmgc2A/a8HY1I03eTV0fZcC8oEMNvdgsKzsUi8LZE/7YTmBXXdwQrMWZcfU8kmdPU3kfVVqQ8ttmri+AcIimriIDsR1mid9Gqt9Np+u3ezHPLjQqdOwhX6xRYTIPlBnZw3SskKCW3u8EJv4RzeNaFkzRb0iD35vFX7EJF0MK3a5PiBFsYU8HsXyG8Ca1Ji4JM48zuj1CyWbG+6hwcfoiKkyQ6zsFbFjAB01gDlkcVudjlTORo5TZ93SNax7D4nMMyHuzuqaZHl2m3uuS9yJLsCeV/HdB9M8AsBzsM4ObQga6hnYC+9Gae9tKRgSTOUnGjLcvo1l1qLVXtnGnIbPHTFF5t5HWLRGI3iQk+7zfBFYWJCxe+HM5V2OqylACwVmpj5RTu/1WKQtUfZ9pXW7IqX7t24OvPcASMGYfpJwLycZA8qNG3KoE6/pqOPhlrgna8UeWRnjQnGEsrt8zYE+8EcE+SsRpMLZNUHic=
  on:
    tags: true
