#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop babag-api.service >/dev/null
fi
# End automatically added section

# Automatically added by dh_installinit
if [ -x "/etc/init.d/babag-api" ] || [ -e "/etc/init/babag-api.conf" ]; then
	invoke-rc.d babag-api stop || exit $?
fi
# End automatically added section
